---
- name: Check if Crowdsec is installed
  command: cscli version
  register: crowdsec_installation_check
  ignore_errors: yes
  changed_when: false

- name: Install Crowdsec (if not present)
  block:
    - name: Copy Crowdsec installation script
      copy:
        src: install-crowdsec.sh
        dest: /tmp/install-crowdsec.sh
        mode: '0755'

    - name: Run Crowdsec installation script
      command: /tmp/install-crowdsec.sh

    - name: Ensure Crowdsec service is running
      service:
        name: crowdsec
        state: started
        enabled: yes

  when: crowdsec_installation_check.rc != 0

- name: Check if agent has already registered
  stat: 
    path: /etc/crowdsec/local_api_credentials.yaml
  register: local_api_file
  
- name: Register agent with central server
  command: cscli lapi register -u {{ crowdsec_server_url }} --machine {{ inventory_hostname }}
  args:
    creates: /etc/crowdsec/.enrolled
  when: not local_api_file.stat.exists
  notify: restart crowdsec

- name: Install bouncers dependencies
  apt:
    name:
      - lua5.1
      - libnginx-mod-http-lua
      - luarocks
      - gettext-base
      - lua-cjson
    state: present

- name: Install iptables bouncer
  apt:
    name: crowdsec-firewall-bouncer-iptables
    state: present

- name: Install nginx bouncer
  apt:
    name: crowdsec-nginx-bouncer
    state: present

- name: Add collections
  command: cscli collections install {{ item }}
  loop:
    - crowdsecurity/linux
    - crowdsecurity/sshd
    - crowdsecurity/http-cve
    - crowdsecurity/whitelist-good-actors
    - crowdsecurity/iptables
    - crowdsecurity/nginx
  notify: restart crowdsec
