---
- name: restart docker
  service: 
    name: docker
    state: restarted
    
- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted

- name: restart blackbox_exporter
  service:
    name: blackbox_exporter
    state: restarted

- name: restart nginx_exporter
  service:
    name: nginx_exporter
    state: restarted
