---
- name: restart monitoring stack
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_dir }}"
    state: restarted

- name: restart crowdsec stack
  community.docker.docker_compose_v2:
    project_src: "{{ crowdsec_dir }}"
    state: restarted
