---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Create jail.local from template
  template:
    src: jail.conf
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban

- name: Ensure fail2ban is running
  service:
    name: fail2ban
    state: started
    enabled: yes
